/**
 * Credential loading.
 *
 * Forge does not store SMTP credentials of its own. job-outreach-cli
 * already holds a working Gmail configuration, and duplicating those
 * secrets into a second file means two places to rotate and two places
 * to leak from. Instead this reads that config at runtime, so there is
 * one source of truth.
 *
 * Resolution order:
 *
 *   1. OUTREACH_CLI_CONFIG — explicit path to the existing YAML config
 *   2. Forge's own .env (GMAIL_USER / GMAIL_APP_PASSWORD, or SMTP_*)
 *
 * Nothing here logs a secret. `describe()` exists so a caller can show
 * what was loaded without printing the password.
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { config } from '../config.js';

/**
 * Minimal YAML reader for the flat key/value and one-level-nested
 * shape job-outreach-cli writes.
 *
 * A full YAML parser is a dependency we do not need: the file is
 * generated by a dataclass dump, so its structure is predictable. If
 * the shape ever changes, loading fails loudly rather than silently
 * returning a partial config.
 */
function parseSimpleYaml(text) {
  const root = {};
  const stack = [{ indent: -1, obj: root }];

  for (const rawLine of text.split('\n')) {
    const line = rawLine.replace(/\t/g, '  ');
    if (!line.trim() || line.trim().startsWith('#')) continue;

    const indent = line.length - line.trimStart().length;
    const trimmed = line.trim();
    const sep = trimmed.indexOf(':');
    if (sep === -1) continue;

    const key = trimmed.slice(0, sep).trim();
    let value = trimmed.slice(sep + 1).trim();

    while (stack.length > 1 && indent <= stack[stack.length - 1].indent) {
      stack.pop();
    }
    const parent = stack[stack.length - 1].obj;

    if (value === '' || value === '{}' || value === 'null') {
      const child = {};
      parent[key] = value === 'null' ? null : child;
      if (value === '') stack.push({ indent, obj: child });
      continue;
    }

    // Strip surrounding quotes.
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    if (value === 'true' || value === 'false') parent[key] = value === 'true';
    else if (/^-?\d+$/.test(value)) parent[key] = Number.parseInt(value, 10);
    else if (/^-?\d*\.\d+$/.test(value)) parent[key] = Number.parseFloat(value);
    else parent[key] = value;
  }

  return root;
}

/** Candidate locations for the existing CLI config, most explicit first. */
function candidatePaths() {
  const out = [];
  if (process.env.OUTREACH_CLI_CONFIG) out.push(process.env.OUTREACH_CLI_CONFIG);
  const home = os.homedir();
  out.push(
    path.join(home, '.outreach-cli', 'config.yaml'),
    path.join(home, '.outreach-cli', 'config.yml'),
    path.join(home, '.jobright-email-cli', 'config.yaml')
  );
  return out;
}

/**
 * Load SMTP settings.
 *
 * Returns a normalized object; throws with an actionable message when
 * nothing usable is found, rather than failing later inside nodemailer
 * with an opaque auth error.
 */
export function loadSmtpCredentials({ configPath } = {}) {
  const paths = configPath ? [configPath] : candidatePaths();

  for (const p of paths) {
    let raw;
    try {
      raw = fs.readFileSync(p, 'utf8');
    } catch {
      continue;
    }

    const parsed = parseSimpleYaml(raw);
    const email = parsed.email ?? parsed;

    if (email?.smtp_user && email?.smtp_password) {
      return {
        source: p,
        host: email.smtp_host ?? 'smtp.gmail.com',
        port: email.smtp_port ?? 587,
        user: email.smtp_user,
        pass: email.smtp_password,
        fromEmail: email.from_email || email.smtp_user,
        fromName: email.from_name ?? '',
        // Sender details the templates reference. Taken from the same
        // config so the signature matches what the CLI already sends.
        phone: email.phone ?? '',
        linkedinUrl: email.linkedin_url ?? '',
        website: email.website ?? '',
        jobTitle: email.job_title ?? '',
        resumePath: email.resume_path ?? '',
      };
    }
  }

  // Fall back to Forge's own environment.
  const g = config.mail.gmail;
  if (g.user && g.appPassword) {
    return {
      source: '.env (GMAIL_*)',
      host: 'smtp.gmail.com',
      port: 587,
      user: g.user,
      pass: g.appPassword,
      fromEmail: config.mail.from.address || g.user,
      fromName: config.mail.from.name ?? '',
      phone: '',
      linkedinUrl: '',
      website: '',
      jobTitle: '',
      resumePath: '',
    };
  }

  const s = config.mail.smtp;
  if (s.host && s.user && s.pass) {
    return {
      source: '.env (SMTP_*)',
      host: s.host,
      port: s.port,
      user: s.user,
      pass: s.pass,
      fromEmail: config.mail.from.address || s.user,
      fromName: config.mail.from.name ?? '',
      phone: '',
      linkedinUrl: '',
      website: '',
      jobTitle: '',
      resumePath: '',
    };
  }

  throw new Error(
    'No SMTP credentials found. Either set OUTREACH_CLI_CONFIG to the ' +
      'existing job-outreach-cli config.yaml, or set GMAIL_USER and ' +
      'GMAIL_APP_PASSWORD in Forge/.env.'
  );
}

/** Safe summary for logs — never includes the password. */
export function describe(creds) {
  return {
    source: creds.source,
    host: creds.host,
    port: creds.port,
    user: creds.user,
    from: creds.fromName ? `${creds.fromName} <${creds.fromEmail}>` : creds.fromEmail,
    passwordSet: Boolean(creds.pass),
  };
}
